### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by CedricBell** [inteam-eu-org/chocolo#6]
- [ ] Création d'un logo digne de ce nom
- [ ] Une fois crée, refaire les différentes tailles d’icônes à intégrer dans le ficher **manifest.json** via [PWABuilder](https://www.pwabuilder.com/imageGenerator)

**Comment by Chocorean** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Better picture](https://trello.com/c/px0G5SXL/1-better-picture)

**Comment by Chocorean** [comment]
KAN-1

**Comment by Chocorean** [comment]
c good merci @CedricBell
