### ISSUE TITLE
La zone cliquable pour skip les questions ne prend pas tout l'ecran

### ISSUE THREAD

**Issue by Chocorean** [inteam-eu-org/chocolo#9]
![image](https://github.com/inteam-eu-org/chocolo/assets/11725034/a3029e6d-e2b4-426f-b25c-f2f97eaffd07)

**Comment by Chocorean** [comment]
@CedricBell si t'as le time sinon osef

**Comment by CedricBell** [comment]
Fixed in https://github.com/inteam-eu-org/chocolo/pull/20
